# Generated by Django 5.0.6 on 2024-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_categoria_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(),
        ),
    ]
