# Generated by Django 5.0.6 on 2024-05-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.unidade'),
        ),
    ]
