# Generated by Django 5.0.6 on 2024-05-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.unidade'),
        ),
    ]
