# Generated by Django 5.0.6 on 2024-05-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
